version: '3.9'
services:
  redis:
    image: redis:7
    restart: unless-stopped

  watcher:
    build: ./watcher
    volumes:
      - ./data/input:/input
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./worker
    volumes:
      - ./data/input:/input
      - ./data/output:/output
      - ./data/tmp:/tmp
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
