FROM python:3.11-slim
RUN apt-get update && apt-get install -y ocrmypdf tesseract-ocr imagemagick && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ../requirements.txt .
RUN pip install -r requirements.txt
COPY worker.py .
CMD ["python", "worker.py"]
